# Define networks that can be used by services in the Docker Compose file
networks:
  rag-network:
    driver: bridge

# Define the services that make up your app
services:
  # Define a service name qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db # For developing
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

  # Define a service name rag-api
  rag-api:
    build: .
    container_name: rag_api_service # For developing
    ports:
      - "8080:8080"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PHOENIX_COLLECTOR_ENDPOINT=http://phoenix:4317
    depends_on:
      - qdrant
      - phoenix    
    networks:
      - rag-network

  # Phoenix for monitoring
  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix_server
    ports:
      - "6006:6006"
      - "4317:4317"
    environment:
      - PHOENIX_PORT=6006
    networks:
      - rag-network

  # Define the Streamlit UI service
  streamlit-ui:
    build: 
      context: .
      dockerfile: Dockerfile.ui
    container_name: streamlit_ui_service
    ports:
      - "8501:8501"
    depends_on:
      - rag-api
    networks:
      - rag-network